### ISSUE TITLE
To fix favicon and profile not loading change it to /profile.jpeg

### ISSUE THREAD

**Issue by alicicek** [Vandivier/not-johns-linktree#5]
The profile and favicon weren't loading for me but I fixed it by changing the
` <link rel="icon" href="/not-johns-linktree/favicon.png" />`
` <Profile path="/not-johns-linktree/profile.jpeg" />`

to

` <link rel="icon" href="favicon.png" />`
`<Profile path="/profile.jpeg" />`

**Comment by Vandivier** [comment]
i think this is a behavior on the dev server right? the deployed site works, so i'm not sure it's high priority

there should be some way to fix it so we see it in both places though. a build config option or using env vars are two approaches. not crazy about using env vars bc it means we are kind of developing code and seeing it locally in a way that it won't be built in prod

**Comment by alicicek** [comment]
im new to coding so not sure what those mean but It took me time to get it working on my local host
________________________________

**Comment by Vandivier** [comment]
looks like i already have an env-toggle code in the next config file:
```
const debug = process.env.NODE_ENV !== "production";

module.exports = {
  assetPrefix: !debug ? "/not-johns-linktree/" : "",
  // images: { loader: "imgix" },
  // reactStrictMode: true,
};
```

**Comment by Vandivier** [comment]
resolved!
